### ISSUE TITLE
Rename module to PriNCe and move tests into prince directory

### ISSUE THREAD

**Issue by afedynitch** [joheinze/PriNCe#32]
I think one last change that would break the examples and should be done before reaching milestone is the renaming of the module to PriNCe.
On the same note I recommend/prefer pulling the tests into the prince package folder. This has some more academic implications, like prevention from triggering local imports that can the correctness of paths etc. I have seen that many packages do it like this and also have done it successfully in MCEq. Pytest expects this and will find these tests by default.

**Comment by joheinze** [comment]
OK, I agree. I can take care of this, once the open Pull request #31 is closed
